language: node_js
node_js:
  - "0.10"
before_script:
  - npm install -g jshint@2.5.5
  - npm install -g jscs@1.6.0
script:
  - "jshint *.js && jscs *.js"
notifications:
 irc:
   channels:
     - "chat.freenode.net#mediawiki-visualeditor"
